# Generated by Django 3.2.15 on 2023-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizs',
            name='users_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
