runtime: python37

env_variables:
  # This setting is used in settings.py to configure your ALLOWED_HOSTS
  APPENGINE_URL: quizgame-django.uc.r.appspot.com

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /media
  static_dir: media/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto